### ISSUE TITLE
support for podman

### ISSUE THREAD

**Issue by lzumot** [eugeneyan/obsidian-copilot#1]
Hi i had a few issues when tryign to run with podman
##########################
I had to make changes to makefile change makefile: replace all docker with podman (alias docker=podman nto enough asyou ahve to modify docker-network and docker-compose as well as remove buildkit and add --format docker
e.g.:
podman-network:
	podman network create ${NETWORK} || true
...
opensearch: podman-network
	podman run ....
...
	podman build --format docker -t ${IMAGE_TAG} -f Dockerfile .
...
	podman run ....
...
	podman-compose up # need to do pip install podman-compose if you don't have it
...

##########################
need to  mkdir data in the repo directory as it was failing make opensearch
##########################
need to explicitly set env again or place in bashrc in new terminal when doing make build-artifacts or replace the makefile params with your own
##########################
instructions could be clearer that make opensearch should be stopped for make run to work

**Comment by eugeneyan** [comment]
Thanks for the feedback! I've made a few changes to:
- Add the data dir to the repo
- Updated the instructions to make clear the opensearch container should be stopped

Would you like to update the Makefile to include podman support?

**Comment by lzumot** [comment]
ill submit a PR with changes to makefile

**Comment by eugeneyan** [comment]
Thanks to @lzumot for adding podman support via PR https://github.com/eugeneyan/obsidian-copilot/pull/3!
