### ISSUE TITLE
`make opensearch` fails with permissions issues

### ISSUE THREAD

**Issue by crypdick** [eugeneyan/obsidian-copilot#11]
Running `make opensearch` fails with a `java.nio.file.AccessDeniedException`. [Full trace here](https://gist.github.com/crypdick/36fd7d61d546ecae60cb2e57f98b0ea8).

Things I've tried:
* added `command: chown -R 1000:root /usr/share/opensearch/data` to the `opensearch` service in  `docker-compose.yml`.
* manually created a few of the folders in the cloned repo, e.g. `./obsidian-copilot/data/nodes`. This was a game of wack-a-mole as more files/folders were missing.

**Comment by eugeneyan** [comment]
`make build` was completed successfully?

And it seem the cause may be the PerformanceAnalyzer? I rebuilt mine from scratch and saw this in the logs

```
[o.o.p.h.c.PerformanceAnalyzerConfigAction] [6ae61205e3dc] PerformanceAnalyzer Enabled: false
```

**Comment by crypdick** [comment]
@eugeneyan yep, I did all the prior steps including `make build`. Thanks for that insight. I tried to add this to the opensearch service in docker-compose.yml:

```
    # disable PerformanceAnalyzerApp, which is causing errors in `make opensearch`
    # https://opensearch.org/docs/latest/monitoring-your-cluster/pa/index/#disable-performance-analyzer
    command: bash -c "
    curl -XPOST localhost:9200/_plugins/_performanceanalyzer/rca/cluster/config -H 'Content-Type: application/json' -d '{\"enabled\": false}' &&
    kill $(ps aux | grep -i 'PerformanceAnalyzerApp' | grep -v grep | awk '{print $2}') &&
    curl -XPOST localhost:9200/_plugins/_performanceanalyzer/cluster/config -H 'Content-Type: application/json' -d '{\"enabled\": false}'
    "
```

...however, it didn't seem to make any difference and I still get the same trace with `java.nio.file.AccessDeniedException: /usr/share/opensearch/data/thread_contention_monitoring_enabled.conf`. The container doesn't crash, though, and just to be sure I tried running `make build-artifacts` in a separate terminal. It fails to talk to opensearch (`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='opensearch', port=9200): Max retries exceeded with url: [...] Name or service not known'`)

**Comment by crypdick** [comment]
Here's another thing that didn't work. I moved the disable commands to their own file:

```bash
#!/bin/bash
# disable PerformanceAnalyzerApp, which is causing errors in `make opensearch`
# https://opensearch.org/docs/latest/monitoring-your-cluster/pa/index/#disable-performance-analyzer
curl -XPOST localhost:9200/_plugins/_performanceanalyzer/rca/cluster/config -H 'Content-Type: application/json' -d '{"enabled": false}' &&
kill $(ps aux | grep -i 'PerformanceAnalyzerApp' | grep -v grep | awk '{print $2}') &&
curl -XPOST localhost:9200/_plugins/_performanceanalyzer/cluster/config -H 'Content-Type: application/json' -d '{"enabled": false}' &&
bin/opensearch-plugin remove opensearch-performance-analyzer
```

I gave it executable permissions. Then I added this to the `make opensearch` `docker run` command: `-v ./opensearch_entrypoint.sh:/opensearch_entrypoint.sh --entrypoint /opensearch_entrypoint.sh `

However, it looks like the curl command needs to run after the service is already running: `curl: (7) Failed to connect to localhost port 9200 after 0 ms: Couldn't connect to server`

**Comment by crypdick** [comment]
I solved the issue by changing the entrypoint file as follows:

```bash
#!/bin/bash
# disable PerformanceAnalyzerApp, which is causing errors in `make opensearch`
# https://opensearch.org/docs/latest/monitoring-your-cluster/pa/index/#disable-performance-analyzer
bin/opensearch-plugin remove opensearch-performance-analyzer
bin/opensearch-plugin remove opensearch-observability
chown -R 1000:root /usr/share/opensearch/data/
./opensearch-docker-entrypoint.sh opensearch
```

I had to remove opensearch-observability due to an unrelated downstream issue being thrown by that plugin. I also had to change the permissions of the data folder.

**Comment by eugeneyan** [comment]
Thank you for persisting with this 🙇
