### ISSUE TITLE
Add linter and formatter pre-commit hook

### ISSUE THREAD

**Issue by crypdick** [eugeneyan/obsidian-copilot#15]
Hi @eugeneyan, thanks for the awesome work here. I've only been using this plugin for a few days and it's already been super awesome.

As I work on my own fork, I'm injecting subconsciously injecting my personal coding conventions which clash with yours (preference for `"` over `'`, linebreaks, trailing commas, etc. I think it would be great if there were some pre-commit hooks to keep consistent conventions.

**Comment by eugeneyan** [comment]
Thanks for all the pull requests Richard! I'm glad you found the plugin useful.

Yea, ideally we'd have a linter at pre-commit, but then again, I didn't expect others (like yourself!) to contribute to it so enthusiastically. I might find time to add a linter and other python checks (though my main intent for making this repo public was to show people that (i) lexical search is _still_ pretty useful, (ii) you can generate your own embeddings _locally_, and (iii) streaming output makes all the difference)

**Comment by crypdick** [comment]
@eugeneyan I'd be happy to submit a PR to add a linter pre-commit hook, github actions test, and also run the linter across the repo. I'm a fan of [ruff](https://github.com/astral-sh/ruff). What do you think?

**Comment by eugeneyan** [comment]
That would be awesome! Thank you 🙏
