### ISSUE TITLE
Is it possible to put my gpt-4 API key somewhere?

### ISSUE THREAD

**Issue by aldopareja** [eugeneyan/obsidian-copilot#2]

**Comment by skiman6010** [comment]
<img width="713" alt="image" src="https://github.com/eugeneyan/obsidian-copilot/assets/8137212/2def6b00-c9ef-4683-8c82-4853c99e0823">

Change "gpt-3.5-turbo" to "gpt-4" and you should be inferencing from gpt-4 after that.
