### ISSUE TITLE
Another Obsidian Copilot

### ISSUE THREAD

**Issue by fizzzib** [eugeneyan/obsidian-copilot#25]
I expect you know this already; there is an Obsidian plugin available from the community library called 'Obsidian Copilot'. I'm not going to get into debate which one was earliest or most popular or whatever. I am hugely grateful for all developers who create plugins. Just pointing out at the very least the clash of names. I'm quite sure there's room for all sorts of AI functionality. Thanks for what you are doing.

**Comment by eugeneyan** [comment]
Thanks for sharing this! Yeap I'm familiar with Obsidian Copilot by Logan. Haha the conflict in names is unfortunate but conveys the spirit of what we're trying to achieve. This will (probably) never become an Obsidian plugin—its intent was to demonstrate how we could build a simple RAG with opensearch and embedding retrieval.
